services:
    rstudio:
        build:
            context: .
        environment:
            - TZ=Europe/Madrid
            - DISABLE_AUTH=true
        volumes:
            - .:/home/rstudio/rabootcamp-docker-2023
            - renv:/home/rstudio/.cache/R/renv

volumes:
  renv:
    external: true